#!/bin/bash
# Copyright (c) 2024-2025 Jesse Morgan / Morgan Forge
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# =============================================================================
# rigrun Installer Script
# The AI coding assistant that respects your terminal
# =============================================================================

set -e

# Colors
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color
BOLD='\033[1m'

# Configuration
RIGRUN_VERSION="${RIGRUN_VERSION:-latest}"
INSTALL_DIR="${INSTALL_DIR:-$HOME/.local/bin}"
CONFIG_DIR="${CONFIG_DIR:-$HOME/.rigrun}"

# =============================================================================
# HELPERS
# =============================================================================

print_logo() {
    echo -e "${PURPLE}"
    cat << 'EOF'

    ██████╗ ██╗ ██████╗ ██████╗ ██╗   ██╗███╗   ██╗
    ██╔══██╗██║██╔════╝ ██╔══██╗██║   ██║████╗  ██║
    ██████╔╝██║██║  ███╗██████╔╝██║   ██║██╔██╗ ██║
    ██╔══██╗██║██║   ██║██╔══██╗██║   ██║██║╚██╗██║
    ██║  ██║██║╚██████╔╝██║  ██║╚██████╔╝██║ ╚████║
    ╚═╝  ╚═╝╚═╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝

EOF
    echo -e "${NC}"
    echo -e "    ${CYAN}The AI coding assistant that respects your terminal${NC}"
    echo ""
}

print_step() {
    echo -e "${PURPLE}▸${NC} $1"
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}!${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

# =============================================================================
# SYSTEM DETECTION
# =============================================================================

detect_os() {
    case "$(uname -s)" in
        Linux*)     OS="linux";;
        Darwin*)    OS="darwin";;
        MINGW*|MSYS*|CYGWIN*) OS="windows";;
        *)          OS="unknown";;
    esac
    echo "$OS"
}

detect_arch() {
    case "$(uname -m)" in
        x86_64|amd64)  ARCH="amd64";;
        arm64|aarch64) ARCH="arm64";;
        *)             ARCH="unknown";;
    esac
    echo "$ARCH"
}

# =============================================================================
# CHECKS
# =============================================================================

check_ollama() {
    if command -v ollama &> /dev/null; then
        if ollama list &> /dev/null; then
            return 0
        fi
    fi
    return 1
}

check_go() {
    if command -v go &> /dev/null; then
        return 0
    fi
    return 1
}

# =============================================================================
# INSTALLATION
# =============================================================================

install_from_source() {
    print_step "Building from source..."

    if ! check_go; then
        print_error "Go is required to build from source"
        print_warning "Install Go from https://golang.org/dl/"
        exit 1
    fi

    # Clone or update
    REPO_DIR="$HOME/.rigrun-src"
    if [ -d "$REPO_DIR" ]; then
        cd "$REPO_DIR"
        git pull
    else
        git clone https://github.com/jeranaias/rigrun-tui.git "$REPO_DIR"
        cd "$REPO_DIR"
    fi

    # Build
    go build -o "$INSTALL_DIR/rigrun" .

    print_success "Built and installed to $INSTALL_DIR/rigrun"
}

create_config() {
    print_step "Creating configuration..."

    mkdir -p "$CONFIG_DIR"
    mkdir -p "$CONFIG_DIR/sessions"
    mkdir -p "$CONFIG_DIR/logs"
    mkdir -p "$CONFIG_DIR/costs"
    mkdir -p "$CONFIG_DIR/benchmarks"

    if [ ! -f "$CONFIG_DIR/config.toml" ]; then
        cat > "$CONFIG_DIR/config.toml" << 'EOF'
# rigrun Configuration
# Generated by installer

[ollama]
url = "http://localhost:11434"
model = "qwen2.5-coder:7b"

[ui]
vim_mode = false
show_costs = true
theme = "dark"

[routing]
default_mode = "auto"
prefer_local = true

[security]
offline_mode = false
classification = "unclassified"

[context]
max_messages = 50
recent_messages = 20
EOF
        print_success "Created config at $CONFIG_DIR/config.toml"
    else
        print_warning "Config already exists, skipping"
    fi
}

setup_ollama() {
    if check_ollama; then
        print_success "Ollama is already installed and running"
        return 0
    fi

    print_warning "Ollama not found"
    echo ""
    echo -e "    Please install Ollama from: ${CYAN}https://ollama.ai${NC}"
    echo ""
    echo "    After installing, run:"
    echo -e "    ${CYAN}ollama serve${NC}"
    echo ""

    read -p "    Press Enter when Ollama is ready (or 's' to skip): " response
    if [ "$response" = "s" ]; then
        print_warning "Skipping Ollama setup"
        return 1
    fi

    return 0
}

download_model() {
    echo ""
    echo -e "    ${BOLD}Choose a model to download:${NC}"
    echo ""
    echo "    1) qwen2.5-coder:7b   (Recommended - Fast & capable)"
    echo "    2) qwen2.5-coder:14b  (Best quality)"
    echo "    3) codestral:22b      (Excellent for code)"
    echo "    4) llama3.1:8b        (General purpose)"
    echo "    5) Skip"
    echo ""

    read -p "    Enter choice [1-5]: " choice

    case $choice in
        1) MODEL="qwen2.5-coder:7b";;
        2) MODEL="qwen2.5-coder:14b";;
        3) MODEL="codestral:22b";;
        4) MODEL="llama3.1:8b";;
        5) print_warning "Skipping model download"; return;;
        *) MODEL="qwen2.5-coder:7b";;
    esac

    print_step "Downloading $MODEL..."
    ollama pull "$MODEL"
    print_success "Model downloaded!"
}

add_to_path() {
    # Check if already in PATH
    if [[ ":$PATH:" == *":$INSTALL_DIR:"* ]]; then
        return 0
    fi

    print_step "Adding to PATH..."

    SHELL_RC=""
    if [ -n "$ZSH_VERSION" ] || [ -f "$HOME/.zshrc" ]; then
        SHELL_RC="$HOME/.zshrc"
    elif [ -n "$BASH_VERSION" ] || [ -f "$HOME/.bashrc" ]; then
        SHELL_RC="$HOME/.bashrc"
    fi

    if [ -n "$SHELL_RC" ]; then
        echo "" >> "$SHELL_RC"
        echo "# rigrun" >> "$SHELL_RC"
        echo "export PATH=\"\$PATH:$INSTALL_DIR\"" >> "$SHELL_RC"
        print_success "Added to $SHELL_RC"
        print_warning "Run 'source $SHELL_RC' or restart your terminal"
    fi
}

# =============================================================================
# MAIN
# =============================================================================

main() {
    clear
    print_logo

    echo -e "    ${BOLD}Welcome to the rigrun installer!${NC}"
    echo ""
    echo "    This will:"
    echo "      ✦ Install rigrun to $INSTALL_DIR"
    echo "      ✦ Create configuration in $CONFIG_DIR"
    echo "      ✦ Set up Ollama (if needed)"
    echo "      ✦ Download a recommended AI model"
    echo ""

    read -p "    Press Enter to continue (or 'q' to quit): " response
    if [ "$response" = "q" ]; then
        exit 0
    fi

    echo ""

    # Create install directory
    mkdir -p "$INSTALL_DIR"

    # Install
    install_from_source

    # Config
    create_config

    # Ollama
    if setup_ollama; then
        download_model
    fi

    # PATH
    add_to_path

    # Done!
    echo ""
    echo -e "${GREEN}╭──────────────────────────────────────────╮${NC}"
    echo -e "${GREEN}│                                          │${NC}"
    echo -e "${GREEN}│       ✨ Installation Complete! ✨       │${NC}"
    echo -e "${GREEN}│                                          │${NC}"
    echo -e "${GREEN}╰──────────────────────────────────────────╯${NC}"
    echo ""
    echo "    You're ready! Start rigrun:"
    echo ""
    echo -e "    ${CYAN}rigrun${NC}"
    echo ""
    echo "    Quick tips:"
    echo -e "      ${CYAN}Ctrl+P${NC}  - Command palette"
    echo -e "      ${CYAN}@file:${NC}  - Include file context"
    echo -e "      ${CYAN}/help${NC}   - Show all commands"
    echo ""
    echo "    Happy coding! 🚀"
    echo ""
}

main "$@"
