# Copyright (c) 2024-2025 Jesse Morgan / Morgan Forge
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# =============================================================================
# rigrun Installer for Windows
# The AI coding assistant that respects your terminal
# =============================================================================

$ErrorActionPreference = "Stop"

# Configuration
$InstallDir = "$env:USERPROFILE\.local\bin"
$ConfigDir = "$env:USERPROFILE\.rigrun"

# Colors
function Write-Purple { Write-Host $args -ForegroundColor Magenta }
function Write-Cyan { Write-Host $args -ForegroundColor Cyan }
function Write-Green { Write-Host $args -ForegroundColor Green }
function Write-Yellow { Write-Host $args -ForegroundColor Yellow }
function Write-Red { Write-Host $args -ForegroundColor Red }

# =============================================================================
# HELPERS
# =============================================================================

function Show-Logo {
    Write-Purple @"

    ██████╗ ██╗ ██████╗ ██████╗ ██╗   ██╗███╗   ██╗
    ██╔══██╗██║██╔════╝ ██╔══██╗██║   ██║████╗  ██║
    ██████╔╝██║██║  ███╗██████╔╝██║   ██║██╔██╗ ██║
    ██╔══██╗██║██║   ██║██╔══██╗██║   ██║██║╚██╗██║
    ██║  ██║██║╚██████╔╝██║  ██║╚██████╔╝██║ ╚████║
    ╚═╝  ╚═╝╚═╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝

"@
    Write-Cyan "    The AI coding assistant that respects your terminal"
    Write-Host ""
}

function Write-Step {
    param($Message)
    Write-Host -NoNewline "  "
    Write-Purple -NoNewline "▸"
    Write-Host " $Message"
}

function Write-Success {
    param($Message)
    Write-Host -NoNewline "  "
    Write-Green -NoNewline "✓"
    Write-Host " $Message"
}

function Write-Warning {
    param($Message)
    Write-Host -NoNewline "  "
    Write-Yellow -NoNewline "!"
    Write-Host " $Message"
}

function Write-Error {
    param($Message)
    Write-Host -NoNewline "  "
    Write-Red -NoNewline "✗"
    Write-Host " $Message"
}

# =============================================================================
# CHECKS
# =============================================================================

function Test-Ollama {
    try {
        $null = Get-Command ollama -ErrorAction Stop
        $null = ollama list 2>$null
        return $true
    } catch {
        return $false
    }
}

function Test-Go {
    try {
        $null = Get-Command go -ErrorAction Stop
        return $true
    } catch {
        return $false
    }
}

# =============================================================================
# INSTALLATION
# =============================================================================

function Install-FromSource {
    Write-Step "Building from source..."

    if (-not (Test-Go)) {
        Write-Error "Go is required to build from source"
        Write-Warning "Install Go from https://golang.org/dl/"
        exit 1
    }

    $RepoDir = "$env:USERPROFILE\.rigrun-src"

    if (Test-Path $RepoDir) {
        Set-Location $RepoDir
        git pull
    } else {
        git clone https://github.com/jeranaias/rigrun-tui.git $RepoDir
        Set-Location $RepoDir
    }

    # Create install directory
    New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null

    # Build
    go build -o "$InstallDir\rigrun.exe" .

    Write-Success "Built and installed to $InstallDir\rigrun.exe"
}

function New-Config {
    Write-Step "Creating configuration..."

    New-Item -ItemType Directory -Force -Path $ConfigDir | Out-Null
    New-Item -ItemType Directory -Force -Path "$ConfigDir\sessions" | Out-Null
    New-Item -ItemType Directory -Force -Path "$ConfigDir\logs" | Out-Null
    New-Item -ItemType Directory -Force -Path "$ConfigDir\costs" | Out-Null
    New-Item -ItemType Directory -Force -Path "$ConfigDir\benchmarks" | Out-Null

    $ConfigFile = "$ConfigDir\config.toml"

    if (-not (Test-Path $ConfigFile)) {
        @"
# rigrun Configuration
# Generated by installer

[ollama]
url = "http://localhost:11434"
model = "qwen2.5-coder:7b"

[ui]
vim_mode = false
show_costs = true
theme = "dark"

[routing]
default_mode = "auto"
prefer_local = true

[security]
offline_mode = false
classification = "unclassified"

[context]
max_messages = 50
recent_messages = 20
"@ | Out-File -FilePath $ConfigFile -Encoding utf8

        Write-Success "Created config at $ConfigFile"
    } else {
        Write-Warning "Config already exists, skipping"
    }
}

function Setup-Ollama {
    if (Test-Ollama) {
        Write-Success "Ollama is already installed and running"
        return $true
    }

    Write-Warning "Ollama not found"
    Write-Host ""
    Write-Host "    Please install Ollama from: " -NoNewline
    Write-Cyan "https://ollama.ai"
    Write-Host ""
    Write-Host "    After installing, run:"
    Write-Cyan "    ollama serve"
    Write-Host ""

    $response = Read-Host "    Press Enter when Ollama is ready (or 's' to skip)"
    if ($response -eq "s") {
        Write-Warning "Skipping Ollama setup"
        return $false
    }

    return $true
}

function Get-Model {
    Write-Host ""
    Write-Host "    Choose a model to download:" -ForegroundColor White
    Write-Host ""
    Write-Host "    1) qwen2.5-coder:7b   (Recommended - Fast & capable)"
    Write-Host "    2) qwen2.5-coder:14b  (Best quality)"
    Write-Host "    3) codestral:22b      (Excellent for code)"
    Write-Host "    4) llama3.1:8b        (General purpose)"
    Write-Host "    5) Skip"
    Write-Host ""

    $choice = Read-Host "    Enter choice [1-5]"

    switch ($choice) {
        "1" { $Model = "qwen2.5-coder:7b" }
        "2" { $Model = "qwen2.5-coder:14b" }
        "3" { $Model = "codestral:22b" }
        "4" { $Model = "llama3.1:8b" }
        "5" { Write-Warning "Skipping model download"; return }
        default { $Model = "qwen2.5-coder:7b" }
    }

    Write-Step "Downloading $Model..."
    ollama pull $Model
    Write-Success "Model downloaded!"
}

function Add-ToPath {
    $currentPath = [Environment]::GetEnvironmentVariable("Path", "User")

    if ($currentPath -like "*$InstallDir*") {
        return
    }

    Write-Step "Adding to PATH..."

    $newPath = "$currentPath;$InstallDir"
    [Environment]::SetEnvironmentVariable("Path", $newPath, "User")

    Write-Success "Added to PATH"
    Write-Warning "Restart your terminal for PATH changes to take effect"
}

# =============================================================================
# MAIN
# =============================================================================

function Main {
    Clear-Host
    Show-Logo

    Write-Host "    Welcome to the rigrun installer!" -ForegroundColor White
    Write-Host ""
    Write-Host "    This will:"
    Write-Host "      ✦ Install rigrun to $InstallDir"
    Write-Host "      ✦ Create configuration in $ConfigDir"
    Write-Host "      ✦ Set up Ollama (if needed)"
    Write-Host "      ✦ Download a recommended AI model"
    Write-Host ""

    $response = Read-Host "    Press Enter to continue (or 'q' to quit)"
    if ($response -eq "q") {
        exit 0
    }

    Write-Host ""

    # Install
    Install-FromSource

    # Config
    New-Config

    # Ollama
    if (Setup-Ollama) {
        Get-Model
    }

    # PATH
    Add-ToPath

    # Done!
    Write-Host ""
    Write-Green "╭──────────────────────────────────────────╮"
    Write-Green "│                                          │"
    Write-Green "│       ✨ Installation Complete! ✨       │"
    Write-Green "│                                          │"
    Write-Green "╰──────────────────────────────────────────╯"
    Write-Host ""
    Write-Host "    You're ready! Start rigrun:"
    Write-Host ""
    Write-Cyan "    rigrun"
    Write-Host ""
    Write-Host "    Quick tips:"
    Write-Host "      " -NoNewline; Write-Cyan "Ctrl+P" -NoNewline; Write-Host "  - Command palette"
    Write-Host "      " -NoNewline; Write-Cyan "@file:" -NoNewline; Write-Host "  - Include file context"
    Write-Host "      " -NoNewline; Write-Cyan "/help" -NoNewline; Write-Host "   - Show all commands"
    Write-Host ""
    Write-Host "    Happy coding! 🚀"
    Write-Host ""
}

Main
